@startuml

title __PRIDE-UTILITIES's Class Diagram__\n

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.impl {
      abstract class AbstractPrecursorIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.impl {
      abstract class AbstractProductIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    enum AminoAcid {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class AminoAcidSequence {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class ApproximateComparator {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    enum Atom {
    }
  }
  

  package uk.ac.ebi.pride.utilities.exception {
    class ContaminantFileException {
    }
  }
  

  package uk.ac.ebi.pride.utilities.term {
    enum CvTermReference {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class DateUtils {
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.impl {
      class DefaultPeptideIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.impl {
      class DefaultPrecursorIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.impl {
      class DefaultProductIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    enum Element {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.file {
      class FileUtil {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.ion {
      class FragmentIonType {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.ion {
      class FragmentIonTypeColor {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.ion {
      class FragmentIonUtilities {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class GraviUtilities {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class Group {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class IOUtilities {
    }
  }
  

  package uk.ac.ebi.pride.utilities.exception {
    class IllegalAminoAcidSequenceException {
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.impl {
      class ImmoniumIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class InternetChecker {
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      class IonCleavageException {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class IsoelectricPointUtils {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    interface Mass {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.file {
      enum MassSpecFileFormat {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.file {
      class MassSpecFileRegx {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.contaminant {
    class MatchContaminant {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.Math {
      class MathUtils {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class MoleculeUtilities {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class MoleculeUtilities {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class NeutralLoss {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    enum NuclearParticle {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class NumberUtilities {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class PTModification {
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      class Peak {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      class PeakSet {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    class Peptide {
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      interface PeptideIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      class PeptideScore {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      interface PrecursorIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      interface ProductIon {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class ProductIonFactory {
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    enum ProductIonPair {
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.model {
      class ProductIonSet {
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.mol {
    enum ProductIonType {
    }
  }
  

  package uk.ac.ebi.pride.utilities.term {
    enum QuantCvTermReference {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class RegExUtilities {
    }
  }
  

  package uk.ac.ebi.pride.utilities.term {
    enum SearchEngineCvTermReference {
    }
  }
  

  package uk.ac.ebi.pride.utilities.term {
    enum SearchEngineScoreCvTermReference {
    }
  }
  

  package uk.ac.ebi.pride.utilities.engine {
    enum SearchEngineType {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class StringUtils {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class Triple {
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    class Tuple {
    }
  }
  

  AbstractPrecursorIon -up-|> PrecursorIon
  AbstractPrecursorIon -up-|> DefaultPeptideIon
  AbstractProductIon -up-|> ProductIon
  AbstractProductIon -up-|> Comparable
  AbstractProductIon -up-|> DefaultPeptideIon
  AbstractProductIon o-- PrecursorIon : precursorIon
  AbstractProductIon o-- ProductIonType : type
  AminoAcid -up-|> Mass
  AminoAcidSequence -up-|> Mass
  Atom -up-|> Mass
  ContaminantFileException -up-|> IOException
  DefaultPeptideIon -up-|> PeptideIon
  DefaultPeptideIon o-- Peptide : peptide
  DefaultPrecursorIon -up-|> AbstractPrecursorIon
  DefaultProductIon -up-|> AbstractProductIon
  FragmentIonType -up-|> Cloneable
  ImmoniumIon -up-|> Comparable
  ImmoniumIon o-- AminoAcid : acid
  ImmoniumIon o-- PTModification : modification
  NeutralLoss -up-|> Mass
  NeutralLoss -up-|> Cloneable
  NuclearParticle -up-|> Mass
  Peak -up-|> Comparable
  PeakSet -up-|> TreeSet
  PeakSet o-- ApproximateComparator : comparator
  Peptide o-- Group : n_terminal
  Peptide o-- Group : c_terminal
  PeptideScore o-- PeakSet : peakSet
  PeptideScore o-- PrecursorIon : precursorIon
  PeptideScore o-- ProductIonPair : ionPair
  ProductIonSet -up-|> TreeSet
  ProductIonType o-- FragmentIonType : group
  ProductIonType o-- NeutralLoss : loss
  ProductIonType o-- ProductIonPair : pair
  SearchEngineScoreCvTermReference o-- SearchEngineCvTermReference : searchEngineParam
  Triple -up-|> Serializable
  Triple o-- K : first
  Triple o-- V : second
  Triple o-- T : third
  Tuple -up-|> Serializable
  Tuple o-- K : key
  Tuple o-- V : value


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
