@startuml

title __FILE's Class Diagram__\n

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.file {
      class FileUtil {
          {static} + DOT : String
          - FileUtil()
          {static} + getFileExtension()
          {static} + getFileExtension()
          {static} + isBinaryFile()
          {static} + tail()
          {static} + getDecompressedFileName()
          {static} + getRealFileName()
          {static} + getFileInputStream()
          {static} + isZipped()
          {static} + isGzipped()
          {static} + isFileEmpty()
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.file {
      enum MassSpecFileFormat {
        MGF
        MZML
        MZIDENTML
        PRIDE
        DAT
        XTANDEM
        PKL
        PKL_SPO
        SEQUEST_DTA
        SEQUEST_OUT
        OMSSA_OMX
        MSGF
        SPECTRAST
        CRUX
        PEPTIDE_PROPHET
        PROTEIN_PROPHET
        PROTEIN_PILOT
        VEMS_PKX
        MS2
        MZDATA
        MZXML
        MZTAB
        BRUKER_BAF
        BRUKER_FID
        BRUKER_YEP
        ABI_WIFF
        ABI_SCAN
        ABI_MTD
        RAW
        AGILENT_MASSHUNTER_RAW
        IBD
        IMG
        IMZML
        HDR
        FASTA
        TIF
        GIF
        PNG
        JPG
        fileExtension
        fileFormat
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.util {
    package uk.ac.ebi.pride.utilities.util.file {
      class MassSpecFileRegx {
          {static} + PRIDE_XML_PATTERN : Pattern
          {static} + MZML_PATTERN : Pattern
          {static} + MZIDENTML_PATTERN : Pattern
          {static} + MZXML_PATTERN : Pattern
          {static} + MZDATA_PATTERN : Pattern
          - MassSpecFileRegx()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
