@startuml

title __EXCEPTION's Class Diagram__\n

  package uk.ac.ebi.pride.utilities.exception {
    class ContaminantFileException {
        + ContaminantFileException()
    }
  }
  

  class WrappedPrintWriter {
      - printWriter : PrintWriter
      ~ WrappedPrintWriter()
      ~ lock()
      ~ println()
  }
  

  class WrappedPrintStream {
      - printStream : PrintStream
      ~ WrappedPrintStream()
      ~ lock()
      ~ println()
  }
  

  abstract class PrintStreamOrWriter {
      - PrintStreamOrWriter()
      {abstract} ~ lock()
      {abstract} ~ println()
  }
  

  class SentinelHolder {
      {static} + STACK_TRACE_ELEMENT_SENTINEL : StackTraceElement
      {static} + STACK_TRACE_SENTINEL : StackTraceElement[]
      - SentinelHolder()
  }
  

  package uk.ac.ebi.pride.utilities.exception {
    class IllegalAminoAcidSequenceException {
        + IllegalAminoAcidSequenceException()
        + IllegalAminoAcidSequenceException()
        + IllegalAminoAcidSequenceException()
        + IllegalAminoAcidSequenceException()
    }
  }
  

  class WrappedPrintWriter {
      - printWriter : PrintWriter
      ~ WrappedPrintWriter()
      ~ lock()
      ~ println()
  }
  

  class WrappedPrintStream {
      - printStream : PrintStream
      ~ WrappedPrintStream()
      ~ lock()
      ~ println()
  }
  

  abstract class PrintStreamOrWriter {
      - PrintStreamOrWriter()
      {abstract} ~ lock()
      {abstract} ~ println()
  }
  

  class SentinelHolder {
      {static} + STACK_TRACE_ELEMENT_SENTINEL : StackTraceElement
      {static} + STACK_TRACE_SENTINEL : StackTraceElement[]
      - SentinelHolder()
  }
  

  ContaminantFileException -up-|> IOException
  ContaminantFileException +-down- WrappedPrintWriter
  ContaminantFileException +-down- WrappedPrintStream
  ContaminantFileException +-down- PrintStreamOrWriter
  ContaminantFileException +-down- SentinelHolder
  IllegalAminoAcidSequenceException +-down- WrappedPrintWriter
  IllegalAminoAcidSequenceException +-down- WrappedPrintStream
  IllegalAminoAcidSequenceException +-down- PrintStreamOrWriter
  IllegalAminoAcidSequenceException +-down- SentinelHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
