@startuml

title __ION's Class Diagram__\n

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.ion {
      class FragmentIonType {
          {static} + A_ION : FragmentIonType
          {static} + B_ION : FragmentIonType
          {static} + C_ION : FragmentIonType
          {static} + D_ION : FragmentIonType
          {static} + X_ION : FragmentIonType
          {static} + Y_ION : FragmentIonType
          {static} + Z_ION : FragmentIonType
          {static} + V_ION : FragmentIonType
          {static} + W_ION : FragmentIonType
          {static} + AMBIGUOUS_ION : FragmentIonType
          {static} + IMMONIUM_ION : FragmentIonType
          {static} + IN_SOURCE_ION : FragmentIonType
          {static} + CO_ELUTING_ION : FragmentIonType
          {static} + NON_IDENTIFIED_ION : FragmentIonType
          {static} + PRECURSOR_ION : FragmentIonType
          - name : String
          - label : String
          - FragmentIonType()
          + getName()
          + getLabel()
          + equals()
          + hashCode()
          + clone()
          + toString()
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.ion {
      class FragmentIonTypeColor {
          {static} + A_ION_COLOR : Color
          {static} + B_ION_COLOR : Color
          {static} + C_ION_COLOR : Color
          {static} + D_ION_COLOR : Color
          {static} + X_ION_COLOR : Color
          {static} + Y_ION_COLOR : Color
          {static} + Z_ION_COLOR : Color
          {static} + V_ION_COLOR : Color
          {static} + W_ION_COLOR : Color
          {static} + AMBIGUOUS_ION_COLOR : Color
          {static} + IMMONIUM_ION_COLOR : Color
          {static} + IN_SOURCE_ION_COLOR : Color
          {static} + CO_ELUTING_ION_COLOR : Color
          {static} + NON_IDENTIFIED_ION_COLOR : Color
          {static} + PRECURSOR_ION_COLOR : Color
          {static} + getColor()
      }
    }
  }
  

  package uk.ac.ebi.pride.utilities.iongen {
    package uk.ac.ebi.pride.utilities.iongen.ion {
      class FragmentIonUtilities {
          {static} + getFragmentIonType()
          {static} + isBackboneFragmentIonType()
          {static} + isNTerminalFragmentation()
          {static} + isCTerminalFragmentation()
          {static} + isCTerminalSideChainFragmentation()
          {static} + isNTerminalSideChainFragmentation()
          {static} + isImmoniumFragmentation()
          {static} + getFragmentIonNeutralLoss()
      }
    }
  }
  

  FragmentIonType -up-|> Cloneable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
